### ISSUE TITLE
Upgrade to 2.401.2~ynh1 fails and restore fails too

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/jenkins_ynh#113]
### Describe the bug

I just wanted to upgrade Jenkins through webadmin and unfortunately it fails. As restore doesn't work either, I'm left without a working Jenkins installation atm. Please help.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.3
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2.401.2~ynh1
- If upgrading, current package version: none because restore failed too

### Steps to reproduce

I just hit the upgrade button from the webadmin. I couldn't try again with CLI as the whole app was removed afterwards.

### Expected behavior

The app should successfully upgrade.

### Logs
https://paste.yunohost.org/raw/alefosurur

**Comment by yalh76** [comment]
Seems it comes from this error in your log:
```
2023-07-27 06:38:45,189: DEBUG - + out='Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
2023-07-27 06:38:45,190: DEBUG - ERROR: could not open HSTS store at '\''/root/.wget-hsts'\''. HSTS will be disabled.
```
You should fix that before retrying

**Comment by CodeShakingSheep** [comment]
I can't test this anymore but it seems to be the same issue as in #114 which could be solved. So, I'm closing this. Thanks for help.
