### ISSUE TITLE
Installation of 2.401.2~ynh1 fails

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/jenkins_ynh#114]
### Describe the bug

As described in #113 upgrading and restoring failed. So, I wanted to do a fresh install which failed too.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.3
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2.401.2~ynh1

### Steps to reproduce
```sh
sudo yunohost app install jenkins
```

### Expected behavior
The app should be installed successfully.

### Logs
https://paste.yunohost.org/raw/ibezamudos

**Comment by yalh76** [comment]
Seems it comes from this error in your log:
```
2023-07-27 06:19:08,567: DEBUG - + out='Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
2023-07-27 06:19:08,568: DEBUG - ERROR: could not open HSTS store at '\''/root/.wget-hsts'\''. HSTS will be disabled.
```
You should fix that before retrying

**Comment by CodeShakingSheep** [comment]
Thanks for investigating. Indeed, that was the cause. I could fix it with `chmod 644 .wget-hsts` as described [here](https://superuser.com/questions/1539972/wget-error-bash-windows-subsystem-for-linux). Afterwards, installation was successful.
