### ISSUE TITLE
Replace deprecated plugins during installation

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/jenkins_ynh#118]
### Describe the feature request

When doing a fresh install the two following deprecated plugins are being installed:
- [Pipeline: Deprecated Groovy Libraries](https://plugins.jenkins.io/workflow-cps-global-lib)
- [GitHub Organization Folder Plugin](https://plugins.jenkins.io/github-organization-folder)

Both plugins provide replacement plugins on the Jenkins pages.
- [Pipeline Groovy Lib](https://plugins.jenkins.io/pipeline-groovy-lib/)
- [GitHub Branch Source](https://plugins.jenkins.io/github-branch-source/)

I suggest replacing the two deprecated plugins with the replacement plugins during installation.

### Expected behavior

Only actively maintained plugins should be installed by default.

**Comment by yalh76** [comment]
As far as I see those plugins are not directly installed during Jenkins install:
https://github.com/YunoHost-Apps/jenkins_ynh/blob/ae7daa6297953260aa8cde835916fd346107841c/scripts/install#L150-L185

so they should be installed as a dependency of another plugin. Feel free to do a PR if you find a way to solve that

**Comment by CodeShakingSheep** [comment]
GitHub Organization Folder Plugin is directly installed. See l.176 `$jenkins_plugin_manager --plugins github-organization-folder	# GitHub Organization Folder Plugin`. I already created a draft PR for this https://github.com/YunoHost-Apps/jenkins_ynh/pull/122. 

However, Pipeline: Deprecated Groovy Libraries seems to be a dependency of another plugin. I will check this in the upcoming weeks when I find the time and complete the PR.
